# Generated by Django 2.1.2 on 2018-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='t-shirt'),
            preserve_default=False,
        ),
    ]
